### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by jwinters7** [mschiffm/cppip#4]
./cppip -D -f -e timestamp:2015-10-21:08:33:02-2015-10-21:08:33:20 1445412783.cppip 1445412783.pcap.gz carved-1445412783.pcap
extracting from 1445412783.pcap.gz using 1445412783.cppip...
DBG: first pkt ts:		(1445412782) 2015-10-21 07:33:02.690245
DBG: start pkt ts:		(1445412782) 2015-10-21 07:33:02.000000
DBG: stop pkt ts		(1445412800) 2015-10-21 07:33:20.000000
DBG: index level:		1 0
DBG: entered at pkt ts:		2015-10-21 07:33:02.000000
DBG: fuzzy match at iteration:	1
start ts: 2015-10-21 07:33:02.000000 not found, instead fuzzy matched on 2015-10-21 07:33:02.690245
Segmentation fault

(gdb) bt
#0  0x00007ffff7649d6b in __memcpy_ssse3_back () from /lib64/libc.so.6
#1  0x000000000040335f in extract_by_ts (c=0x60b010) at extract.c:367

./cppip -v 1445412783.cppip
valid cppip index file
version:	1.4
created:	2015-11-02 18:53:49.616815
packets in pcap:1633283
indexing mode:	timestamp
index level:	0:0:0:1
record count:	60

I could very likely be doing something incorrectly, let me know if more info is needed.

Also the timestamps I have to input have to be off by and hour or I get an error that the end TS if before the start of the file.

**Comment by mschiffm** [comment]
Hi jwinters7, thanks for the bug report. Does `cppip` work in "packet number" mode? Have you gotten "timestamp" mode to work with different timestamp arguments? What system are you building / running `cppip` on? Also, any chance I can get to work the pcap in question?

**Comment by jwinters7** [comment]
No doesn't work in packet number mode either, it writes a little bit of the new.pcap in either mode though.  I have tried with different timestamps, and even different pcaps, I starting to think its a bit of a bigger problem. I've even tried it on different machines, I'm running on CentOS Linux release 7.1.1503. With 3.10.0-123.8.1.el7.x86_64 kernel. 

Error in messages when trying to use timestamp method:
kernel: cppip[17893]: segfault at 7fffc9f0e000 ip 00007fe754bfc5af sp 00007fffc9f00e28 error 6 in libc-2.17.so[7fe754ab3000+1b6000]

Error in messages when trying to use packet number method: 
kernel: traps: cppip-exec[18843] general protection ip:402d92 sp:7fffb921d288 error:0 in cppip-exec[400000+a000]

The pcaps I'm using are about 600MB compressed, if you think its the pcap I will see if I can create some random non live capture data and see how it handles that. 

Thanks for your response and help with this.

**Comment by mschiffm** [comment]
I can't recreate the issue on Debian (wheezy) or OS X 10.11.1. If you can get me the offending pcap (dropbox?) that would help a ton. If that's too unwieldy, perhaps you can recreate with a smaller pcap?

**Comment by jwinters7** [comment]
Okay, been playing around some more. It does seem to be an issue with certain pcap files, I have one file that it seg faults on when the time window is around 40 seconds. However it works on that same file with a 5 second window. 

I know you need the file to be able to really help more, I'm trying to capture something that I can hand out. However I'm currently having issues reproducing the issue outside of our live traffic. 

I wanted to keep you updated though, I will post a pcap as soon as I find one I can release.

**Comment by mschiffm** [comment]
Happy to help but I need more hard data. :)

**Comment by mschiffm** [comment]
Was able to the crash (big packet, small buffer) -- please pull down the new tree and verify this fixes your issue and I'll close the issue. Thanks!

**Comment by jwinters7** [comment]
Nice work! Impressed since I gave you almost nothing to work with. Love the commit message too, thanks again.
